images:
  api:
    repository: ghcr.io/icipe-official/api
    tag: 0a813c59
  dbMigrations:
    repository: ghcr.io/icipe-official/db-migrations
    tag: latest
  help:
    repository: ghcr.io/icipe-official/help
    tag: 52fb5ebd
  ingestionapi:
    repository: ghcr.io/icipe-official/ingestionapi
    tag: c4d82c87
  tileserver:
    repository: ghcr.io/icipe-official/tileserver
    tag: f331f113
  ui:
    repository: ghcr.io/icipe-official/ui
    tag: "ed389a6d"
  umami:
    repository: ghcr.io/umami-software/umami
    tag: postgresql-v1.40
  nginx:
    tag: eb6a603f
workload-identity-webhook:
  azureTenantID: "dummy" # temporary placeholder
  azureTenantIDFromSecret:
    name: azure-workload-identity
    key: azure-tenant-id
