images:
  api:
    repository: ghcr.io/icipe-official/api
    tag: "0563458d"
  dbMigrations:
    repository: ghcr.io/icipe-official/db-migrations
    tag: latest
  help:
    repository: ghcr.io/icipe-official/help
    tag: bedeb870
  ingestionapi:
    repository: ghcr.io/icipe-official/ingestionapi
    tag: "0563458d"
  tileserver:
    repository: ghcr.io/icipe-official/tileserver
    tag: 070e96a5
  ui:
    repository: ghcr.io/icipe-official/ui
    tag: "7711fa6d"
  umami:
    repository: ghcr.io/umami-software/umami
    tag: postgresql-v1.40
  nginx:
    tag: eb6a603f
  redis:
    repository: redis
    tag: "7"
workload-identity-webhook:
  azureTenantID: "dummy" # temporary placeholder
  azureTenantIDFromSecret:
    name: azure-workload-identity
    key: azure-tenant-id
