apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    {{- if .Values.services.analytics.labels }}
    {{- .Values.services.analytics.labels | toYaml | nindent 4 }}
    {{- end }}
  ports:
    - port: {{ .Values.services.analytics.port }}
      targetPort: {{ .Values.services.analytics.targetPort }}
