apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: analytics
  name: analytics
spec:
  replicas: {{ .Values.deployments.analytics.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: analytics
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.images.umami.repository }}:{{ .Values.images.umami.tag }}
          ports:
            - containerPort: {{ .Values.deployments.analytics.containerPort }}
          env:
            - name: BASE_PATH
              value: {{ .Values.deployments.analytics.env.BASE_PATH | quote }}
            - name: CLIENT_IP_HEADER
              value: {{ .Values.deployments.analytics.env.CLIENT_IP_HEADER | quote }}
            - name: DATABASE_TYPE
              value: {{ .Values.deployments.analytics.env.DATABASE_TYPE | quote }}
            - name: DATABASE_URL
              {{- if .Values.deployments.analytics.env.DATABASE_URL }}
              value: {{ .Values.deployments.analytics.env.DATABASE_URL | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.name }}
                  key: DATABASE_URL_ANALYTICS_UAT
                  optional: false
              {{- end }}
      restartPolicy: Always
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{ .Values.global.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
