apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: analytics
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analytics
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: analytics
    spec:
      containers:
        - name: analytics
          image: ghcr.io/icipe-official/umami:944ba4e
          ports:
            - containerPort: 3000  # Adjust this based on your container's exposed port
          env:
            - name: BASE_PATH
              value: /analytics
            - name: CLIENT_IP_HEADER
              value: x-original-ip
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: DATABASE_URL_ANALYTICS_UAT
                  optional: false
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret

