apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: vectoratlas
spec:
  selector:
    io.kompose.service: analytics  # This should match the label from Deployment
  ports:
    - port: 3000
      targetPort: 3000  # This matches the container port
