apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - command:
            - node
            - dist/src/main.js
          env:
            - name: ANALYTICS_ADMIN_PASSWORD
            - name: ANALYTICS_API_URL
              value: '"http://analytics:3000/analytics/api"'
            - name: AUTH0_AUDIENCE
            - name: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
            - name: AUTH0_ISSUER_URL
            - name: AZURE_STORAGE_CONNECTION_STRING
            - name: BASE_URL
            - name: CONFIG_FOLDER
              value: /etc/vector-atlas/api
            - name: DATACITE_PASSWORD
            - name: DATACITE_PREFIX
            - name: DATACITE_URL
            - name: DATACITE_USER
            - name: DATA_INGESTION_URL
            - name: DATA_VALIDATION_URL
            - name: DB_ENCRYPT_CONNECTION
              value: "false"
            - name: DOI_ENVIRONMENT
            - name: DOI_PUBLISHER
            - name: DOI_RESOLVER_BASE_URL
            - name: EMAIL_FROM
            - name: EMAIL_HOST
            - name: EMAIL_PASSWORD
            - name: EMAIL_PORT
            - name: EMAIL_SECURE
            - name: FILE_STORAGE_TYPE
            - name: IMAP_PORT
            - name: IMAP_SERVER
            - name: NEXT_PUBLIC_ANALYTICS_ID
              value: '"2b3b6da0-3e75-4d9e-be86-d588496a174e"'
            - name: NEXT_PUBLIC_AUTH_ENDPOINT
              value: http://api:3001/auth/token
            - name: NEXT_PUBLIC_TOKEN_KEY
            - name: OVERLAY_BLOB_FOLDER
              value: /data/blobStore/
            - name: POSTGRES_DB
            - name: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
            - name: PUBLIC_FOLDER
              value: /usr/src/app/dist
            - name: SENT_EMAIL_FOLDER
            - name: TEMP_DIR
            - name: TILESERVER_DATA_FOLDER
              value: /data/
            - name: TOKEN_KEY
          image: ghcr.io/icipe-official/api:latest
          name: api
          volumeMounts:
            - mountPath: /usr/src/app/dist/public
              name: api-claim0
            - mountPath: /etc/vector-atlas/api
              name: api-claim1
            - mountPath: /data
              name: api-claim2
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
        - name: api-claim1
          persistentVolumeClaim:
            claimName: api-claim1
        - name: api-claim2
          persistentVolumeClaim:
            claimName: api-claim2
