apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vectoratlas
  labels:
    io.kompose.service: api
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    io.kompose.service: api
  type: ClusterIP

