apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- if .Values.services.api.labels }}
    {{- .Values.services.api.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.services.api.port }}
      targetPort: {{ .Values.services.api.targetPort }}
      protocol: TCP
  selector:
    io.kompose.service: api
  {{- if .Values.services.api.type }}
  type: {{ .Values.services.api.type }}
  {{- end }}
