apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-migrations
  name: db-migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-migrations
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-migrations
    spec:
      containers:
        - command:
            - npm
            - run
            - migrations:runallprod
          env:
            - name: DB_ENCRYPT_CONNECTION
              value: "true"
            - name: POSTGRES_DB
            - name: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: ghcr.io/icipe-official/api:latest
          name: db-migrations
      restartPolicy: Always
