apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-migrations
  name: db-migrations-{{ now | unixEpoch }}
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-migrations
    spec:
      containers:
        - command:
            - npm
            - run
            - migrations:runallprod
          env:
            - name: DB_ENCRYPT_CONNECTION
              value: "true"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_DB_UAT
                  optional: false
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_HOST_UAT
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_PASSWORD_UAT
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_USER_UAT
                  optional: false
          image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}
          name: db-migrations
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ghcr-login-secret
