apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-ui-deployment" .Release.Namespace }}
  namespace: {{ .Values.Namespace}}
  labels:
    app: {{ .Values.Deploymentapplabel}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Podapplabel}}
  template:
    metadata:
      labels:
        app: {{ .Values.Podapplabel}}
    spec: # Pod spec
      containers:
      - name: ui
        image: 51.140.225.217/vector-atlas/ui
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: pgadmin-configmap
