apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: help
  name: help
spec:
  replicas: {{ .Values.deployments.help.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: help
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: help
    spec:
      containers:
        - command: {{ .Values.deployments.help.command | toYaml | nindent 12 }}
          image: {{ .Values.images.help.repository }}:{{ .Values.images.help.tag }}
          name: help
      restartPolicy: Always
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{ .Values.global.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
