apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: help
  name: help
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: help
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: help
    spec:
      containers:
        - command:
            - nginx
            - -g
            - daemon off;
          image: ghcr.io/icipe-official/help:latest
          name: help
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret
