apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name | lower }}-ingestion-api-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.ingress.gateway.name }}
      namespace: {{ .Values.ingress.gateway.namespace }}
      sectionName: {{ .Values.ingress.gateway.section }}
  hostnames:
    - {{ .Values.ingress.routes.ingestion.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.routes.ingestion.path }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ .Values.ingress.routes.ingestion.stripPrefix | quote }}
      backendRefs:
        - name: {{ .Values.ingress.routes.ingestion.backend.service }}
          port: {{ .Values.ingress.routes.ingestion.backend.port }}
