apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map-wms-ingress
  namespace: vectoratlas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /geoserver/Interventions/wms/$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Required when proxying to an HTTPS upstream
spec:
  rules:
    - http:
        paths:
          - path: /map-wms(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: map-wms-service
                port:
                  number: 80

