apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map-wms-ingress
  namespace: vectoratlas
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /geoserver/Interventions/wms$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "data.malariaatlas.org"
spec:
  ingressClassName: nginx
  rules:
  - host: test.vectoratlas.icipe.org
    http:
      paths:
      - path: /map-wms(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: malariaatlas-service
            port:
              number: 443
---
apiVersion: v1
kind: Service
metadata:
  name: malariaatlas-service
  namespace: vectoratlas
spec:
  type: ExternalName
  externalName: data.malariaatlas.org
  ports:
  - port: 443
    protocol: TCP
