apiVersion: v1
kind: Service
metadata:
  name: malariaatlas-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.services.malariaatlas.type }}
  externalName: {{ .Values.services.malariaatlas.externalName | quote }}
  ports:
    - port: {{ .Values.services.malariaatlas.port }}
      protocol: TCP
