apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map-wms-ingress
  namespace: vectoratlas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /geoserver/Interventions/wms/$2  # Rewrite path before forwarding
    nginx.ingress.kubernetes.io/proxy-pass-url: https://data.malariaatlas.org # Direct proxy to external URL
spec:
  rules:
    -http:
      paths:
        - path: /map-wms(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: map-wms-service  # In case a service is required for internal routing
              port:
                number: 80           # Adjust if using internal service (optional)
