apiVersion: batch/v1
kind: Job
metadata:
  name: occurrencegeojob
spec:
  backoffLimit: {{ .Values.deployments.occurrencegeojob.backoffLimit }}
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      securityContext:
        runAsUser: {{ .Values.deployments.occurrencegeojob.securityContext.runAsUser }}
      serviceAccountName: {{ .Values.deployments.occurrencegeojob.serviceAccountName }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{ .Values.global.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.deployments.occurrencegeojob.restartPolicy }}
      containers:
        - name: occurrencegeojob
          image: {{ .Values.images.occurrencegeojob.repository }}:{{ .Values.images.occurrencegeojob.tag }}
          env:
            - name: PGDATABASE
              {{- if .Values.deployments.occurrencegeojob.env.PGDATABASE }}
              value: {{ .Values.deployments.occurrencegeojob.env.PGDATABASE | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.name }}
                  key: POSTGRES_DB_UAT
              {{- end }}
            - name: PGHOST
              {{- if .Values.deployments.occurrencegeojob.env.PGHOST }}
              value: {{ .Values.deployments.occurrencegeojob.env.PGHOST | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.name }}
                  key: POSTGRES_HOST_UAT
              {{- end }}
            - name: PGPASSWORD
              {{- if .Values.deployments.occurrencegeojob.env.PGPASSWORD }}
              value: {{ .Values.deployments.occurrencegeojob.env.PGPASSWORD | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.name }}
                  key: POSTGRES_PASSWORD_UAT
              {{- end }}
            - name: PGUSER
              {{- if .Values.deployments.occurrencegeojob.env.PGUSER }}
              value: {{ .Values.deployments.occurrencegeojob.env.PGUSER | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.name }}
                  key: POSTGRES_USER_UAT
              {{- end }}
            - name: PGPORT
              value: {{ .Values.deployments.occurrencegeojob.env.PGPORT | quote }}
            - name: LOGGER_LEVEL
              value: {{ .Values.deployments.occurrencegeojob.env.LOGGER_LEVEL | quote }}
            - name: LOGGER_OUTPUT
              value: {{ .Values.deployments.occurrencegeojob.env.LOGGER_OUTPUT | quote }}
            - name: TARGET_DIRECTORY
              value: {{ .Values.deployments.occurrencegeojob.env.TARGET_DIRECTORY | quote }}
            - name: STAGING_DIRECTORY
              value: {{ .Values.deployments.occurrencegeojob.env.STAGING_DIRECTORY | quote }}
          volumeMounts:
            - mountPath: /home/app/app/.tmp
              name: occurrencegeojob-volume
      volumes:
        - name: occurrencegeojob-volume
          persistentVolumeClaim:
            claimName: pvc-occurrencedata
