apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  namespace: {{ .Values.Namespace }}  # Reference the namespace from values.yaml
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgAdmin.defaultEmail | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgAdmin.defaultPassword | quote }}
