apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-db-deployment" .Release.Namespace }}
  namespace: {{ .Values.Namespace}}
  labels:
    app: {{ .Values.PostgressDeploymentapplabel}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.PostgressPodapplabel}}
  template:
    metadata:
      labels:
        app: {{ .Values.PostgressPodapplabel}}
    spec: # Pod spec
      containers:
      - name: db
        image: 51.140.225.217/vector-atlas/db
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgress-configmap
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: postgrespvc
