apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: python-backend
  name: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: python-backend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_DB_UAT
                  optional: false
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_HOST_UAT
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_PASSWORD_UAT
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: POSTGRES_USER_UAT
                  optional: false
            - name: POSTGRES_PORT
              value: "5432"
          image: {{ .Values.images.ingestionapi.repository }}:{{ .Values.images.ingestionapi.tag }}
          name: python-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret
