apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: python-backend
  name: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: python-backend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
            - name: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
            - name: POSTGRES_USER
          image: ghcr.io/icipe-official/ingestionapi:latest
          name: python-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
