apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Release.Namespace }}
  namespace: {{ .Values.Namespace}}
  labels:
    app: {{ .Values.Serviceapplabel}}
spec:
  ports:
   - protocol: TCP
     port: 3002
     targetPort: 3000
  selector:
    app: {{ .Values.Podapplabel}}
