apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tileserver-ingress
  namespace: vectoratlas
spec:
  rules:
    -http:
        paths:
          - path: /data
            pathType: Prefix
            backend:
              service:
                name: tileserver  # Name of the service you're routing to
                port:
                  number: 80
