apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name | lower }}-tileserver-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.ingress.gateway.name }}
      namespace: {{ .Values.ingress.gateway.namespace }}
      sectionName: {{ .Values.ingress.gateway.section }}
  hostnames:
    - {{ .Values.ingress.routes.tileserver.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.routes.tileserver.path }}
      backendRefs:
        - name: {{ .Values.ingress.routes.tileserver.backend.service }}
          port: {{ .Values.ingress.routes.tileserver.backend.port }}
