apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tileserver
  name: tileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tileserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: tileserver
    spec:
      containers:
        - image: ghcr.io/icipe-official/tileserver:latest
          name: tileserver
          volumeMounts:
            - mountPath: /data
              name: tileserver-claim0
      restartPolicy: Always
      volumes:
        - name: tileserver-claim0
          persistentVolumeClaim:
            claimName: pvc-data
      imagePullSecrets:
        - name: ghcr-login-secret
