apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.uat.yml -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.uat.yml -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - command:
            - node
            - server.js
          env:
            - name: API_URL
              value: api
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_AUDIENCE_UAT
            - name: AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_BASE_URL_UAT
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_CLIENT_ID_UAT
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_CLIENT_SECRET_UAT
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_ISSUER_BASE_URL_UAT
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: uat-secrets
                  key: AUTH0_SECRET_UAT
            - name: NEXT_PUBLIC_AUTH_ENDPOINT
              value: http://api:3001/auth/token
            - name: NEXT_PUBLIC_TOKEN_KEY
          image: ghcr.io/icipe-official/ui:ddd945b
          name: ui
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret
