apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- if .Values.services.ui.labels }}
    {{- .Values.services.ui.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  selector:
    io.kompose.service: ui
  ports:
    - port: {{ .Values.services.ui.port }}
      targetPort: {{ .Values.services.ui.targetPort }}
      protocol: TCP
  {{- if .Values.services.ui.type }}
  type: {{ .Values.services.ui.type }}
  {{- end }}
