apiVersion: v1
kind: PersistentVolume
metadata:
  name: vectoratlas-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dmmg-kubernetes-test/vector_atlas_db
