apiVersion: v1
kind: PersistentVolume
metadata:
  name: vector-atlas-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dmmgadmin/administration/vectoratlas_db
