# PersistentVolumes

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-api
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dmmg-kubernetes-test/vectoratlas/api
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-public
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dmmg-kubernetes-test/vectoratlas/public
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/dmmg-kubernetes-test/vectoratlas/data
  persistentVolumeReclaimPolicy: Retain

# PersistentVolumeClaims

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-api

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-public

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-data
